services:
  mongo:
    image: mongo
    ports:                                 # Declares the ports to publish (host_port:app_port)
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database  # Database name
    volumes:                               # Bind a file on host to a file in container (host_file:app_file)
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js